In [1]:
import torch
import torch.nn as nn
import torch.optim as optim

# from datasets import load_dataset

# dataset = load_dataset("yelp_review_full")

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [2]:
import pickle
# with open('yelp_dataset.pkl', 'wb') as file:
#     pickle.dump(dataset, file)

In [3]:
with open('yelp_dataset.pkl', 'rb') as file:
    dataset = pickle.load(file)

/opt/homebrew/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [4]:
print(dataset)

DatasetDict({
    train: Dataset({
        features: ['label', 'text'],
        num_rows: 650000
    })
    test: Dataset({
        features: ['label', 'text'],
        num_rows: 50000
    })
})


In [5]:
train_dataset = dataset['train']
test_dataset = dataset['test']

# Convert train and test datasets to arrays
train_data = train_dataset['text']
train_labels = train_dataset['label']
test_data = test_dataset['text']
test_labels = test_dataset['label']

# Convert labels to lists (optional)
# train_labels = train_labels.tolist()
# test_labels = test_labels.tolist()

In [6]:
print(train_data[0])
print(train_labels[0])


dr. goldberg offers everything i look for in a general practitioner.  he's nice and easy to talk to without being patronizing; he's always on time in seeing his patients; he's affiliated with a top-notch hospital (nyu) which my parents have explained to me is very important in case something happens and you need surgery; and you can get referrals to see specialists without having to see him first.  really, what more do you need?  i'm sitting here trying to think of any complaints i have about him, but i'm really drawing a blank.
4


## Preprocess

In [7]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
nltk.download('stopwords')
nltk.download('punkt')

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/revanthgundam/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     /Users/revanthgundam/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [8]:
import sys  
!{sys.executable} -m pip install contractions
import contractions


[notice] A new release of pip is available: 23.2.1 -> 23.3.1
[notice] To update, run: python3.11 -m pip install --upgrade pip


In [24]:
# import re  # Import the regular expressions module

# # use tokenizer to remove punctuation

# def tokenize_text(text):
#     # Replace "!" with "exm" using regular expressions
#     text = re.sub(r'!', ' exm', text)
    
#     expanded_words = []
#     for word in text.split():
#         # using contractions.fix to expand the shortened words
#         expanded_words.append(contractions.fix(word))   
    
#     expanded_text = ' '.join(expanded_words)
#     # print(expanded_text)
    
#     text = expanded_text    
    
#     # replace a-b with a and b
#     text = text.replace('-', ' ')
    
#     tokens = nltk.word_tokenize(text)
    
#     # Add an extra occurrence for all-uppercase words with more than one letter
#     # temp = [word if (len(word) > 1 and word.isupper()) else None for word in tokens]
#     temp = []
#     for word in tokens:
#         if len(word) > 1 and word.isupper():
#             temp.append(word)
#     tokens.extend(x for x in temp if x)
    
#     # convert to lower case
#     tokens = [w.lower() for w in tokens]
#     # dr. = dr and st. = st and so on
#     tokens = [w.replace('.', '') for w in tokens]
    
#     # remove punctuation
#     # tokens = [word for word in tokens if word.isalpha()]
    
#     # Remove stop words
#     stop_words = set(stopwords.words("english"))
#     tokens = [word for word in tokens if word.isalpha() and word not in stop_words]
    
#     return tokens

# # print(train_data[4])
# # tokenize_text(train_data[4])


In [25]:
# tokens = []
# print(len(train_data))

# for i in range(len(train_data)):
#     tokens.append(tokenize_text(train_data[i]))
#     if i % 1000 == 0:
#         print(i)

# # save to pkl file
# with open('yelp_train_tokens_no_stop.pkl', 'wb') as file:
#     pickle.dump(tokens, file)

In [26]:
# import pickle
# from collections import Counter

# # Load the tokenized data
# with open('yelp_train_tokens_no_stop.pkl', 'rb') as file:
#     tokens = pickle.load(file)

# # Define the frequency cutoff threshold
# frequency_cutoff = 10

# # Count word frequencies
# word_counts = Counter(word for tokens_list in tokens for word in tokens_list)

# # Filter out words with counts less than the threshold
# filtered_tokens = [[word for word in tokens_list if word_counts[word] >= frequency_cutoff] for tokens_list in tokens]

# # Save the filtered tokens to a new file
# with open('yelp_train_tokens_filtered.pkl', 'wb') as file:
#     pickle.dump(filtered_tokens, file)

In [27]:
# tokens_test = []
# print(len(test_data))

# for i in range(len(test_data)):
#     tokens_test.append(tokenize_text(test_data[i]))
#     if i % 1000 == 0:
#         print(i)

# with open('yelp_test_tokens_no_stop.pkl', 'wb') as file:
#     pickle.dump(tokens_test, file)

In [28]:
# import pickle
# from collections import Counter

# # Load the tokenized data
# with open('yelp_test_tokens_no_stop.pkl', 'rb') as file:
#     tokens = pickle.load(file)

# # Define the frequency cutoff threshold
# frequency_cutoff = 10

# # Count word frequencies
# word_counts = Counter(word for tokens_list in tokens for word in tokens_list)

# # Filter out words with counts less than the threshold
# filtered_tokens = [[word for word in tokens_list if word_counts[word] >= frequency_cutoff] for tokens_list in tokens]

# # Save the filtered tokens to a new file
# with open('yelp_test_tokens_filtered.pkl', 'wb') as file:
#     pickle.dump(filtered_tokens, file)

In [9]:
import numpy as np

train_tokens = []
with open('yelp_train_tokens_filtered.pkl', 'rb') as file:
    train_tokens = pickle.load(file)

test_tokens = []
with open('yelp_test_tokens_filtered.pkl', 'rb') as file:
    test_tokens = pickle.load(file)
    
print("Loaded tokens")



Loaded tokens


In [10]:
# in train data replace every 1000th word with UNK randomly

import random

for i in range(len(train_tokens)):
    for j in range(len(train_tokens[i])):
        if random.randint(1, 1000) == 1:
            train_tokens[i][j] = 'UNK'
        

In [11]:
# Build the BoW representation manually
# Create a vocabulary by collecting unique words from the training data
vocab = set()
for tokens in train_tokens:
    vocab.update(tokens)

# Create a dictionary to map words to indices in the vocabulary
vocab_dict = {}
for i, word in enumerate(vocab):
    vocab_dict[word] = i

print(len(vocab_dict))
# Initialize BoW matrices for training and testing data


45287


In [32]:
# reduced_train_tokens = train_tokens

# # Build the BoW representation manually
# # Create a vocabulary by collecting unique words from the training data
# vocab_reduced = set()
# for tokens in reduced_train_tokens:
#     vocab_reduced.update(tokens)

# # Create a dictionary to map words to indices in the vocabulary
# vocab_dict_reduced = {}
# for i, word in enumerate(vocab_reduced):
#     vocab_dict_reduced[word] = i

# print(len(vocab_dict_reduced))

# train_bow = np.zeros((len(reduced_train_tokens), len(vocab_reduced)))

# print("bow train")
# # Convert text to BoW vectors
# for i, tokens in enumerate(reduced_train_tokens):
#     if i % 5000 == 0:
#         print(i)
#     for token in tokens:
#         train_bow[i][vocab_dict_reduced[token]] += 1



# reduced_test_tokens = test_tokens[:5000]
# test_bow = np.zeros((len(reduced_test_tokens), len(vocab_reduced)))

# print("bow test")

# for i, tokens in enumerate(reduced_test_tokens):
#     if i % 1000 == 0:
#         print(i)
#     for token in tokens:
#         if token in vocab_dict_reduced:
#             test_bow[i][vocab_dict_reduced[token]] += 1
#         else:    # if there is an unknown word, add it to the UNK column 
#             test_bow[i][vocab_dict_reduced['UNK']] += 1

In [18]:
import torch
import torch.nn as nn
import torch.optim as optim

num_epochs = 4
learning_rate = 0.01
batch_size = 10000

class BoWClassifier(nn.Module):
    def __init__(self, input_size, output_size):
        super(BoWClassifier, self).__init__()
        self.linear = nn.Linear(input_size, output_size)

    def forward(self, x):
        # Pass the input through the linear layer
        out = self.linear(x)
        return out
    
# Define the model
input_size = len(vocab)  # Input size is the size of the vocabulary
output_size = 5  # Output size is 5 dimensions

model = BoWClassifier(input_size, output_size).to(device)

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=learning_rate)

In [21]:
# # Training loop
# for epoch in range(num_epochs):
#     total = 0
#     correct = 0
#     for i in range(0, len(train_tokens), batch_size):
        
#         inputs = train_tokens[i:i + batch_size]
#         # print(len(inputs))
#         # print(len(vocab))
        
#         # make bow vector for inputs
#         bow = torch.zeros((batch_size, len(vocab)), dtype=torch.float32)
#         # print(bow.shape)
#         for j in range(batch_size):
#             for token in inputs[j]:

#                 bow[j][vocab_dict[token]] += 1

        
#         # convert bow to tensor
#         inputs = torch.tensor(bow, dtype=torch.float32).to(device)
        
#         labels = train_labels[i:i + batch_size]  # Make sure to have train_labels defined
#         # Convert labels to LongTensors
#         labels = torch.tensor(labels, dtype=torch.long).to(device)

#         # Zero the parameter gradients
#         optimizer.zero_grad()

#         # Forward pass
#         outputs = model(inputs)

#         # Calculate the loss
#         loss = criterion(outputs, labels)

#         # Backpropagation
#         loss.backward()

#         # Update weights
#         optimizer.step()

#         # calculate accuracy
#         _, predicted = torch.max(outputs.data, 1)
#         total += labels.size(0)
#         # correct += (predicted == labels).sum().item()
#         # if predicted == labels:
#         #     correct += 1
#         # if |predicted - labels| == 1:
#         #     correct += 0.75
#         # if |predicted - labels| == 2:
#         #     correct += 0.5
#         # if |predicted - labels| == 3:
#         #     correct += 0.25
#         # if |predicted - labels| == 4:
#         #     correct += 0




#         # Print the loss for this batch if needed
#         print(f'Epoch [{epoch+1}/{num_epochs}], Batch [{i//batch_size+1}], Loss: {loss.item()}, Accuracy: {100 * correct / total} %')

#     print(f'Accuracy of the network on the {total} train inputs: {100 * correct / total} %')

# print('Training finished')

# Training loop
for epoch in range(num_epochs):
    total = 0
    correct = 0
    for i in range(0, len(train_tokens), batch_size):
        
        inputs = train_tokens[i:i + batch_size]
        
        # make bow vector for inputs
        bow = torch.zeros((batch_size, len(vocab)), dtype=torch.float32)
        for j in range(batch_size):
            for token in inputs[j]:
                bow[j][vocab_dict[token]] += 1

        # convert bow to tensor
        inputs = torch.tensor(bow, dtype=torch.float32).to(device)
        
        labels = train_labels[i:i + batch_size]
        labels = torch.tensor(labels, dtype=torch.long).to(device)

        # Zero the parameter gradients
        optimizer.zero_grad()

        # Forward pass
        outputs = model(inputs)

        # Calculate the loss
        loss = criterion(outputs, labels)

        # Backpropagation
        loss.backward()

        # Update weights
        optimizer.step()

        # Calculate accuracy based on differences between predicted and actual labels
        _, predicted = torch.max(outputs.data, 1)
        total += labels.size(0)
        for j in range(batch_size):
            diff = abs(predicted[j] - labels[j])
            if diff == 0:
                correct += 1
            elif diff == 1:
                correct += 0.75
            elif diff == 2:
                correct += 0.5
            elif diff == 3:
                correct += 0.25

        # Print the loss for this batch and accuracy
        print(f'Epoch [{epoch+1}/{num_epochs}], Batch [{i//batch_size+1}], Loss: {loss.item()}, Accuracy: {100 * correct / total} %')

    print(f'Accuracy of the network on the {total} train inputs: {100 * correct / total} %')

print('Training finished')


/var/folders/31/d7g63tw141g81ynhx4f_hngr0000gn/T/ipykernel_38372/1891355772.py:82: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  inputs = torch.tensor(bow, dtype=torch.float32).to(device)


Epoch [1/4], Batch [1], Loss: 1.4408131837844849, Accuracy: 80.7725 %
Epoch [1/4], Batch [2], Loss: 1.4724866151809692, Accuracy: 80.28125 %
Epoch [1/4], Batch [3], Loss: 1.4061048030853271, Accuracy: 79.5775 %
Epoch [1/4], Batch [4], Loss: 1.3453079462051392, Accuracy: 79.920625 %
Epoch [1/4], Batch [5], Loss: 1.3129788637161255, Accuracy: 80.5085 %
Epoch [1/4], Batch [6], Loss: 1.2893041372299194, Accuracy: 80.955 %
Epoch [1/4], Batch [7], Loss: 1.2474092245101929, Accuracy: 81.34678571428572 %
Epoch [1/4], Batch [8], Loss: 1.2326922416687012, Accuracy: 81.693125 %
Epoch [1/4], Batch [9], Loss: 1.2362111806869507, Accuracy: 81.96333333333334 %
Epoch [1/4], Batch [10], Loss: 1.2036726474761963, Accuracy: 82.21475 %
Epoch [1/4], Batch [11], Loss: 1.191344976425171, Accuracy: 82.43772727272727 %
Epoch [1/4], Batch [12], Loss: 1.1764874458312988, Accuracy: 82.66375 %
Epoch [1/4], Batch [13], Loss: 1.1839802265167236, Accuracy: 82.82692307692308 %
Epoch [1/4], Batch [14], Loss: 1.17145848

In [22]:
# save the above model in its entirety in pkl file
torch.save(model, 'bow_final_model.pkl')

# load the model
model = torch.load('bow_final_model.pkl')

In [23]:
from sklearn.metrics import f1_score, precision_score, recall_score, confusion_matrix, classification_report

# Test the model
with torch.no_grad():
    total = 0
    correct = 0
    predictions = []
    true_labels = []

    for i in range(0, len(test_tokens), batch_size):
        inputs = test_tokens[i:i + batch_size]
        bow = torch.zeros((batch_size, len(vocab)), dtype=torch.float32)

        for j in range(batch_size):
            for token in inputs[j]:
                if token in vocab_dict:
                    bow[j][vocab_dict[token]] += 1
                else:
                    bow[j][vocab_dict['UNK']] += 1

        inputs = torch.tensor(bow, dtype=torch.float32).to(device)
        labels = test_labels[i:i + batch_size]
        labels = torch.tensor(labels, dtype=torch.long).to(device)

        outputs = model(inputs)

        _, predicted = torch.max(outputs.data, 1)
        total += labels.size(0)
        # correct += (predicted == labels).sum().item()
        for j in range(batch_size):
            diff = abs(predicted[j] - labels[j])
            if diff == 0:
                correct += 1
            elif diff == 1:
                correct += 0.75
            elif diff == 2:
                correct += 0.5
            elif diff == 3:
                correct += 0.25

        # Collect predictions and true labels
        predictions.extend(predicted.cpu().numpy())
        true_labels.extend(labels.cpu().numpy())

    # Calculate accuracy
    accuracy_odrinal = 100 * correct / total
    print(f'Ordinal Accuracy of the network on the {total} test inputs: {accuracy_odrinal} %')

    # Calculate confusion matrix, precision, recall, and F1 scores
    confusion = confusion_matrix(true_labels, predictions)
    classification_rep = classification_report(true_labels, predictions, target_names=[str(i) for i in range(5)])
    f1_micro = f1_score(true_labels, predictions, average='micro')
    f1_macro = f1_score(true_labels, predictions, average='macro')
    f1_weighted = f1_score(true_labels, predictions, average='weighted')
    precision = precision_score(true_labels, predictions, average='weighted')
    recall = recall_score(true_labels, predictions, average='weighted')

    print("Confusion Matrix:")
    print(confusion)
    print("Classification Report:")
    print(classification_rep)
    # print("F1 Micro:", f1_micro)
    # print("F1 Macro:", f1_macro)
    # print("F1 Weighted:", f1_weighted)
    # print("Precision:", precision)
    # print("Recall:", recall)


/var/folders/31/d7g63tw141g81ynhx4f_hngr0000gn/T/ipykernel_38372/393453365.py:21: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  inputs = torch.tensor(bow, dtype=torch.float32).to(device)


Ordinal Accuracy of the network on the 50000 test inputs: 86.425 %
Confusion Matrix:
[[7865 1492  300   87  256]
 [2939 4417 1958  347  339]
 [ 658 1932 4499 1958  953]
 [ 183  328 1722 3746 4021]
 [ 202  105  328 1326 8039]]
Classification Report:
              precision    recall  f1-score   support

           0       0.66      0.79      0.72     10000
           1       0.53      0.44      0.48     10000
           2       0.51      0.45      0.48     10000
           3       0.50      0.37      0.43     10000
           4       0.59      0.80      0.68     10000

    accuracy                           0.57     50000
   macro avg       0.56      0.57      0.56     50000
weighted avg       0.56      0.57      0.56     50000

